// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var rectMove, y, yPosition;
    y = 0;
    if ($('html').hasClass('on')) {
      yPosition = function() {
        y = Math.abs($("article").offset().top);
        return $("#scrollPosition").text("SCROLL POSITION：" + y);
      };
    }
    $("#wrap").scroll(function() {
      yPosition();
      if (y > 700 && y < 900) {
        return $(".rect.scroll").stop().animate({
          marginLeft: 500
        }, 1000, 'linear');
      } else if (y > 900 || y < 700) {
        return $(".rect.scroll").stop().animate({
          marginLeft: 0
        }, 1000, 'linear');
      }
    });
    window.addEventListener("touchstart", yPosition, false);
    window.addEventListener("touchmove", yPosition, false);
    window.addEventListener("touchend", yPosition, false);
    rectMove = function() {
      return $(".rect.move").animate({
        marginLeft: 500
      }, 1000, function() {
        return $(".rect.move").animate({
          marginLeft: 0
        }, 1000);
      });
    };
    setInterval(rectMove, 1000, 1000);
    $(".toggle").click(function() {
      return $(".rect.toggle").animate({
        opacity: "toggle"
      }, 2000);
    });
    if ($('html').hasClass('off')) {
      return $(window).scroll(function() {
        y = $(window).scrollTop();
        return $("#scrollPosition").text("SCROLL POSITION：" + y);
      });
    }
  });

}).call(this);
