// Copyright (c) 2013 NAOTONE (Naoto Yoshimoto) Licensed under the MIT license. 
// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var rectMove, y, yPosition;
    y = 0;
    yPosition = function() {
      y = Math.abs($("article").offset().top);
      return $("#scrollPosition").text("SCROLL POSITION：" + y);
    };
    $("#wrap").scroll(function() {
      yPosition();
      if (y > 700 && y < 900) {
        return $("section#sample2 p").stop().animate({
          marginLeft: 500
        }, 1000, 'linear');
      } else if (y > 900 || y < 700) {
        return $("section#sample2 p").stop().animate({
          marginLeft: 0
        }, 1000, 'linear');
      }
    });
    window.addEventListener("touchstart", yPosition, false);
    window.addEventListener("touchmove", yPosition, false);
    window.addEventListener("touchend", yPosition, false);
    rectMove = function() {
      return $(".rect.move").animate({
        marginLeft: 500
      }, 1000, function() {
        return $(".rect.move").animate({
          marginLeft: 0
        }, 1000);
      });
    };
    setInterval(rectMove, 1000, 1000);
    return $(".toggle").click(function() {
      return $(".rect.toggle").animate({
        opacity: "toggle"
      }, 2000);
    });
  });

}).call(this);
